#!/bin/bash

#file_to_patch="theme_fffc1d0c187715bb8991ef837036a073.css"            # file to split
file_to_patch=`ls ./ | grep theme*.css | grep -v bak`                 # or more wild-card expression
split_selector=".activitystream-posts-comments-container .actions"     # css selector at which to split
stringi=""

# assuming file is minified, splitting it at selector into two lines
find ./$file_to_patch -type f -print0 | xargs -0 perl -i.bak -pe s/"$split_selector"/"\n$split_selector"/g

# split file into two
split -l 1 $file_to_patch

# add extensions to include files
find . -name "xa*" -print0 | xargs -0 file | sed 's/:.*//' | xargs -I % mv % %.css

# prepare include commands for main css file
ls xa* > filelist.tmp
exec 0<filelist.tmp
while read LINE
do
  stringi+=\@import\ url\($LINE\)\;
done

echo $stringi > $file_to_patch

# cleanup
rm ./*.bak ./*.tmp > /dev/null
