#!/bin/bash

file_to_patch=`ls ./ | grep theme*.css | grep -v bak`
split_selector=".activitystream-posts-comments-container .actions"

# break file into two lines
find ./theme_* -type f -print0 | xargs -0 perl -i.bak -pe s/"$split_selector"/"\n$split_selector"/g

# split files into smaller pieces
split -l 1 $file_to_patch

find . -name "xa*" -print0 | xargs -0 file | sed 's/:.*//' | xargs -I % mv % %.css

string12="@import url('xaa.css');@import url('xab.css');@import url('xac.css');@import url('xad.css');@import url('xae.css');"

echo $string12 > $file_to_patch
